name: Deploy python
on:
  push:
    branches:
      - master
jobs:
  run-python:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: list directory
        run:  |
          dir
          cd src/pydemo
          dir
          python --version
      - name: Check python file
        run: python src/pydemo/check.py
      - name: Upload python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dep_files
          path: new.txt